language: r
dist: trusty
sudo: false

cache:
  packages: true

matrix:
  include:
    - name: "Analysis"
      env:
        - BOOK_CHAPTERS="intro,starting,analysis,"
    - name: "Modeling"
      env:
        - BOOK_CHAPTERS="starting,modeling,pipelines"
    - name: "Advanced"
      env:
        - BOOK_CHAPTERS="starting,extensions,distributed-r,streaming"

script:
  - |
    Rscript -e 'testthat::test_dir("tests/testthat/", stop_on_failure = TRUE)'
