language: r
dist: trusty
sudo: false

cache:
  packages: true

matrix:
  include:
    - name: "Analysis"
      env:
        - BOOK_CHAPTERS="intro,starting,analysis,data"
      r_packages:
        - sparklyr
        - bench
        - corrr
        - dbplot
        - readr
    - name: "Modeling"
      env:
        - BOOK_CHAPTERS="starting,modeling,pipelines"
      r_packages:
        - sparklyr
        - callr
        - dbplot
        - FactoMineR
        - forcats
        - ggmosaic
        - httr
        - plumber
        - tidyr
    - name: "Advanced"
      env:
        - BOOK_CHAPTERS="starting,extensions,distributed-r,streaming,contributing"
      r_packages:
        - bench
        - broom
        - digest
        - future
        - ggplot2
        - ggraph
        - graphframes
        - RCurl
        - rsample
        - sparktf
        - sparkxgb
        - tidytext
        - tfdatasets
        - variantspark
        - webreadr

script:
  - |
    Rscript -e 'testthat::test_dir("tests/testthat/", stop_on_failure = TRUE)'
